### ISSUE TITLE
Errors in training

### ISSUE THREAD

**Issue by jontsanders** [mohamedkeid/Feed-Forward-Style-Transfer#2]
I'm trying to run the training on TF 1.3.0 and Python 3.5.2. Everything was normal up until this error at Epoch 280. After this error, the next Loss result is a NaN error. Every subsequent epoch returns "Loss nan"

> INFO:root:Epoch 000280 | Loss 1.147085
> /usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py:29: RuntimeWarning: invalid value encountered in reduce
>  return umr_minimum(a, axis, None, out, keepdims)
> /usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py:26: RuntimeWarning: invalid value encountered in reduce
>  return umr_maximum(a, axis, None, out, keepdims)
> INFO:root:Epoch 000290 | Loss nan

I thought the model might still work so I let it run all the way through training, and tried to test an image against the model. I got the same error:

>/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py:29: RuntimeWarning: invalid value encountered in reduce
  >return umr_minimum(a, axis, None, out, keepdims)
> /usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py:26: RuntimeWarning: invalid value encountered in reduce
  > return umr_maximum(a, axis, None, out, keepdims)

Any thoughts?

**Comment by jontsanders** [comment]
For reference the style and content images I used are here: https://imgur.com/a/4vz5fn6

**Comment by mkeid** [comment]
Hey! Sorry this is so late. I haven't had my computer set up to run any these since I moved to Austin. Getting to it ASAP. I hypothesize this may have to do with the size of the images. Can you try running this with images around ~(512x512)px ? Thanks! Sorry again for the delay.

**Comment by jontsanders** [comment]
Oh, no worries. Thank you for getting back to me. As it happens I'm moving and my computer that can do the stuff is in storage. Once I get a chance I will re-run these.

I will say that with the benefit of a couple month's additional experience since I submitted the support request I think you may be right.... but I'll get back to you in case there is a real bug/real mystery here. Thank you!
