### ISSUE TITLE
test

### ISSUE THREAD

**Issue by zxj11838** [mohamedkeid/Feed-Forward-Style-Transfer#4]
The model obtained by training has always displayed parameter errors during the test. As follow:

E:\PycharmProjects\style-transfer\Feed-Forward-Style-Transfer-master\src>python test.py --styles
Available styles:
starry-night

E:\PycharmProjects\style-transfer\Feed-Forward-Style-Transfer-master\src>python test.py --input G:\picture\friend.jpg --styles starry-night
usage: test.py [-h] [--input INPUT] [--style STYLE] [--out OUT] [--styles]
test.py: error: unrecognized arguments: starry-night

**Comment by mkeid** [comment]
The solution to your problem is in the usage message. Use --style to specify the art.
